---
- hosts: all
  user: admin
  sudo: yes

  vars_files:
    - "../variables.yml"

  tasks:
    - name: Mesosphere apt repository key is set
      apt_key:
        keyserver=keyserver.ubuntu.com
        id=E56151BF
        state=present

    - name: Mesosphere apt repository is set
      apt_repository:
        repo="deb http://repos.mesosphere.io/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} main"
        state=present
        update_cache=yes

    - name: Basic tools are installed
      apt:
        pkg="{{item}}"
        update_cache=yes
        cache_valid_time=3600
        state=present
      with_items:
        - openjdk-7-jdk
        - emacs
        - curl

- include: mesosphere_setup_masters.yml
- include: mesosphere_setup_slaves.yml