---
- hosts: upper_mesosphere
  user: admin
  sudo: yes

  vars_files:
    - "../variables.yml"

  tasks:
    - name: Mesosphere packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - mesos
        - marathon

    - name: Zookeeper id is set
      template:
        src=templates/zookeeper_id.j2
        dest=/etc/zookeeper/conf/myid
        owner=root
        group=root
        mode=0644

    - name: Zookeeper node mapping is ok
      template:
        src=templates/zookeeper_conf.j2
        dest=/etc/zookeeper/conf/zoo.cfg
        backup=yes
        owner=root
        group=root
        mode=0644
      notify: Restart zookeeper

    - name: Mesos masters point to zookeeper
      template:
        src=templates/mesos_zk_conf.j2
        dest=/etc/mesos/zk
        owner=root
        group=root
        mode=0644
      notify: Restart mesos-master

    - name: Mesos quorum is set
      template:
        src=templates/mesos_quorum.j2
        dest=/etc/mesos-master/quorum
        owner=root
        group=root
        mode=0644
      notify: Restart mesos-master

    - name: Marathon config directory is created
      file:
        path=/etc/marathon/conf
        state=directory
        owner=root
        group=root
        mode=0755

    - name: Mesos hostname is set on public DNS
      template:
        src=templates/public_hostname.j2
        dest="{{ item }}"
        owner=root
        group=root
        mode=0644
      with_items:
        - /etc/mesos-master/hostname
        - /etc/marathon/conf/hostname
      notify: Restart mesos-master

    - name: Mesosphere system services are enabled
      service:
        name="{{ item }}"
        enabled=yes
        state=started
      with_items:
        - zookeeper
        - mesos-master
        - marathon

    - name: Mesosphere unused system services are disabled
      service:
        name=mesos-slave
        enabled=no
        state=stopped

  handlers:
    - name: Restart marathon
      service:
        name=marathon
        state=restarted

    - name: Restart mesos-master
      service:
        name=mesos-master
        state=restarted
      notify: Restart marathon

    - name: Restart zookeeper
      service:
        name=zookeeper
        state=restarted
      notify: Restart mesos-master
